### ISSUE TITLE
Deprecate this repository now that it has been merged upstream

### ISSUE THREAD

**Issue by Ambrevar** [dochang/emms-player-mpv#12]
I was wondering what your plans were regarding this repository.

I would recommend deprecating this location and forwarding to the official Emms repo.

I would also recommend removing the package from MELPA.

What do you think?

**Comment by dochang** [comment]
I think we can deprecate this repository once EMMS releases a new version.  After the new version released, I'll remove emms-player-mpv from MELPA & MELPA stable.  Users can upgrade their packages smoothly.

Also, I'm going to update emms-player-mpv to display a warning message about this migration.  This message will also be added to README.

What about this plan?

**Comment by Ambrevar** [comment]
Sounds great, thanks!

**Comment by dochang** [comment]
Close #12 by [1].

[1]: https://github.com/melpa/melpa/commit/5bb66a3e7667552f5a1df36548b9b259c102d12d
