### ISSUE TITLE
first time user changing the volume, Playback channels: nil

### ISSUE THREAD

**Issue by iambumblehead** [dochang/emms-player-mpv#13]
I saw your reddit announcement and decided to try emms for the first time. I'm playing audio files, but when I engage 'emms-volume-mode-plus or 'emms-volume-mode-minus, the message "Playback channels: nil" appears and volume does not change.

Some additional comments here. I do not want to be rude by posting these but as a newnew user my objective thoughts may be useful. 

 * getting started could be easier. "Add $this to .emacs, enter M-x emms, etc"
 * the README here says "audio-display=no" and it would be simpler to give a shell command `$ echo "audio-display=no" >> ~/.config/mpv/config.mpv`
 * a general "emms-mode" similar to emms-volume-mode could be useful for someone running an entire emacs window for the emms player. My favourite music player "moc" [music on console](https://github.com/jonsafari/mocp) provides a standalone text music player with easy navigation and intuitive controls not requiring M-x or C-c combinations, for example 'p' or 'space' to play, '[' and ']' to seek and '<' and '>' to change volume. It does not feel like emms offers an "easy mode" that can do this, but instead requires reading and familiarity with details and hotkeys etc. more of an "advanced mode" only

**Comment by iambumblehead** [comment]
also, when I played an audio file for the first time, the preview image embedded inside the audio was huge and filled my desktop with no close button visible. If emms does not manage the image, I recommend disabling it by default.

**Comment by dochang** [comment]
Thank you for your feedback!  :handshake:

> I'm playing audio files, but when I engage 'emms-volume-mode-plus or 'emms-volume-mode-minus, the message "Playback channels: nil" appears and volume does not change.

I believe that you need to debug [`emms-volume-amixer-change`][1].  It seems that `with-temp-buffer` returns `nil`.  It's not an issue of emms-player-mpv.

[1]: https://git.savannah.gnu.org/cgit/emms.git/tree/lisp/emms-volume-amixer.el?id=c90a7535ff1e6552274adf3a48b777316ff8d897#n60

> getting started could be easier. "Add $this to .emacs, enter M-x emms, etc"

I realize that README is a little bit wordy, maybe we can simplify it.  But I think `$this` would confuse the Emacs newbies.  We should keep README easy to understand. 

> the README here says "audio-display=no" and it would be simpler to give a shell command $ echo "audio-display=no" >> ~/.config/mpv/config.mpv

We should consider the users who are not good at shell command.

> a general "emms-mode" similar to emms-volume-mode could be useful for someone running an entire emacs window for the emms player. My favourite music player "moc" music on console provides a standalone text music player with easy navigation and intuitive controls not requiring M-x or C-c combinations, for example 'p' or 'space' to play, '[' and ']' to seek and '<' and '>' to change volume. It does not feel like emms offers an "easy mode" that can do this, but instead requires reading and familiarity with details and hotkeys etc. more of an "advanced mode" only

Have a look at [emms-browser]?  Well, I don't use it, so I can't give you more help.

Emacs is a customizable editor.  You can bind the keys to any command.  Feel free to build you own player!

Emacs is a self-documenting editor.  This means you can lookup keys and commands whenever and wherever in the editor.  So you should just learn the basic keys and commands, then use EMMS, and lookup any keys and commands as you need.

[emms-browser]: https://www.gnu.org/software/emms/manual/#The-Browser

> also, when I played an audio file for the first time, the preview image embedded inside the audio was huge and filled my desktop with no close button visible. If emms does not manage the image, I recommend disabling it by default.

```
$ echo "audio-display=no" >> ~/.config/mpv/config.mpv
```

:slightly_smiling_face:

**Comment by dochang** [comment]
@iambumblehead This project is just a player backend of EMMS.  It's merging into EMMS and will be deprecated in the future.  You can post your issues on the [EMMS mailing list][1].

I close this issue.  Feel free to reply.

[1]: https://www.gnu.org/software/emms/manual/#Getting-Help
