### ISSUE TITLE
Disable pop-up windows while playing audio

### ISSUE THREAD

**Issue by sheepduke** [dochang/emms-player-mpv#5]
Hi,

It's quite annoying if MPV keeps popping up a window while one just wants to listen to audios.
`--quiet` and `--really-quiet` actually does not work with blocking popping up windows.

`--no-video` should do the trick.

Do you mind adding it? Or provide some configure options maybe? :helicopter: :smile: 

Thanks.

**Comment by alezost** [comment]
@sheepduke, see https://github.com/dochang/emms-player-mpv/pull/3.

**Comment by sheepduke** [comment]
Ah, it's my fault. I didn't see that.

Thanks for a lot of help :-D
