### ISSUE TITLE
Requires CL Library

### ISSUE THREAD

**Issue by abunaideshou** [dochang/emms-player-mpv#6]
Emacs throws an error on initialization unless you add

`(require 'cl)`

to .emacs above where you load emms-player-mpv.

The error is `Symbol's function definition is void: mapcan`

I found how to fix it from here:
https://lists.gnu.org/archive/html/help-gnu-emacs/2013-12/msg00382.html

**Comment by dochang** [comment]
Are you sure the error is from emms-player-mpv?  I don't get this error.  Maybe it's from emms, which calls `mapcan` in [emms-player-mpd.el][1].

[1]: http://git.savannah.gnu.org/cgit/emms.git/tree/lisp/emms-player-mpd.el#n153

**Comment by abunaideshou** [comment]
Yes, after closer inspection, this appears to be an issue with emms-player-mpd.  Strangely, this didn't appear until after I added the emms-player-mpv forms to .emacs.

The relevant --debug-init clearly states where the issue arises, and, as you suspected, the culprit is emms-player-mpd rather than emms-player-mpv.
