### ISSUE TITLE
Adding the --no-audio-display parameter

### ISSUE THREAD

**Issue by Ambrevar** [dochang/emms-player-mpv#8]
That was already mentioned quite a few times in the comment and I believe it would be a sane default as it does not deter from watching videos. What do you think?

Either way, that would definitely deserve some comment in the README :)

**Comment by dochang** [comment]
But some people would like to display image attachments.  I think we should leave this option unspecified.  You can put `audio-display=no` in your config file.

I will update README.

Feel free to reopen this issue.

**Comment by Ambrevar** [comment]
Emms can already display external covers...

**Comment by Ambrevar** [comment]
I think you misunderstood my point though: I am merely talking about making this the _default_ behaviour, and it would be up to the user to enable the display of embedded covers with

```
(setq emms-player-mpv-parameters (delete "--no-audio-display" emms-player-mpv-parameters))
```

I believe most user will find satisfaction with Emms displaying external covers in the browser and the playlist.
Most users probably won't like being bothered with an extra window.

P.S.: I don't have the rights to re-open this issue ;)

**Comment by dochang** [comment]
I want to follow mpv's behavior as possible.  I mean, by default, if mpv displays image attachments, so does emms-player-mpv; if mpv does not, neither do emms-player-mpv.

If you think the default value of `audio-display` should be `no`, you'd better fix mpv rather than emms-player-mpv.
